load 'deploy'

# rails asset pipeline
load 'deploy/assets'

# override assets:update_asset_mtimes
load 'config/assets'

# project configuration
load 'config/deploy'

# db management tasks
load 'config/db'

# server management tasks
load 'config/project'
